service:
  labels:
    app: blackbox-exporter

serviceMonitor:
  enabled: true
  targets:
    - name: postgres-service
      url: postgres://postgres:postgres@postgres-service.student-api.svc.cluster.local:5432/postgres?sslmode=disable
      interval: 60s
      module: http_2xx
      scrapeTimeout: 60s