prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        app: postgres-exporter
    namespaceSelector:
      any: true

kube-state-metrics:
  enabled: true

node-exporter:
  enabled: true

# kubernetes_sd_configs
# prometheus:
#   prometheusSpec:
#     serviceMonitorSelector:
#       matchLabels:
#         app: postgres-exporter
#     namespaceSelector:
#       any: true
#     additionalScrapeConfigs:
#       - job_name: 'kubernetes-pods'         # A custom job name
#         kubernetes_sd_configs:
#           - role: pod
#         relabel_configs:
#           - source_labels: [__meta_kubernetes_pod_label_app]
#             action: keep
#             regex: postgres-exporter        # Scrape only pods labeled app=postgres-exporter
