# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
prometheus:
  additionalServiceMonitors:
    - name: postgres-exporter
      selector:
        matchLabels:
          app: postgres-exporter   
      namespaceSelector:
        matchNames:
          - student-api   
      endpoints:
        - port: http  
          interval: 30s
          path: /metrics
          scheme: http

# grafana:
#   additionalDataSources:
#     - name: Loki
#       type: loki
#       access: proxy
#       url: http://loki-stack.observability.svc.cluster.local:3100
#       isDefault: false
#       basicAuth: false
#       jsonData:
#         tlsSkipVerify: true
#       # secureJsonData:
#       #   basicAuthPassword: U7eQMwrXNHrlR4i43NuBfMhSJluSxgGe8Feo2nRp
#       # basicAuthUser: admin
#       orgId: 1
#       version: 1
#       editable: true


 