# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
prometheus:
  additionalServiceMonitors:
    - name: postgres-exporter
      selector:
        matchLabels:
          app: postgres-exporter   
      namespaceSelector:
        matchNames:
          - student-api   
      endpoints:
        - port: http  
          interval: 30s
          path: /metrics
          scheme: http

#  http://loki-stack.observability.svc.cluster.local:3100/metrics
# http://loki-stack:3100 also working withou any config lets use this.
# solution worked:- https://github.com/grafana/loki/issues/3346