# Values_Prometheous.yaml

# Minimal values.yaml for Prometheus Helm Chart

# serviceMonitors:
#   enabled: true                         # Enable ServiceMonitor discovery

# serviceMonitorSelector:                 # Allow Prometheus to select specific ServiceMonitors
#   matchLabels:
#     app: postgres-exporter               # This should match the label in the PostgreSQL Exporter ServiceMonitor

# namespaceSelector:
#   any: true                             # Optional: Allow Prometheus to select ServiceMonitors across namespaces


# kubeStateMetrics:
#   enabled: true                  # Enable kube-state-metrics

# nodeExporter:
#   enabled: true                  # Enable node-exporter



additionalServiceMonitors:
  - name: postgres-exporter
    selector:
      matchLabels:
        app: postgres-exporter
    namespaceSelector:
      matchNames:
        - observability  # Replace <namespace> with the namespace where your PostgreSQL exporter is running
    endpoints:
      - port: http
        interval: 30s
        path: /metrics
        # scrapeTimeout: 10s

grafana:
  additionalDataSources:
    - name: PostgreSQL Exporter
      type: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090  # Update with your Prometheus service name and namespace
      isDefault: false
      editable: true

      # kube-prometheus-stack-prometheus