.PHONY: docker-compose-up-students-api docker-compose-down-students-api
 
# Start the students-api service
docker-compose-up-students-api:
	docker compose up -d 

# Stop the students-api service
docker-compose-down-students-api:
	docker compose down 


