apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.secretStore.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.vault.server }}
      path: {{ .Values.secretStore.vault.path }}
      version: {{ .Values.secretStore.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.secretStore.vault.tokenSecretRef.name }}
          key: {{ .Values.secretStore.vault.tokenSecretRef.key }}
