---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.pv.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  storageClassName: {{ .Values.postgres.pv.storageClassName }}
  capacity:
    storage: {{ .Values.postgres.pv.capacity.storage }}
  accessModes:
    - {{ .Values.postgres.pv.accessModes }}
  hostPath:
    path: {{ .Values.postgres.pv.hostPath  }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  storageClassName: {{ .Values.postgres.pvc.storageClassName  }}
  accessModes:
    - {{ .Values.postgres.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.resources.requests.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.deployment.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  replicas: {{ .Values.postgres.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.deployment.appLabel }}
    spec:
      nodeSelector:
        type: {{ .Values.postgres.deployment.nodeSelector }}
      containers:
      - name: {{ .Values.postgres.deployment.container.name }}
        image: {{ .Values.postgres.deployment.container.image }}
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.secrets.name }}
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.secrets.name }}
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.secrets.name }}
              key: POSTGRES_USER
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: {{ .Values.postgres.deployment.container.port }}
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.targetPort }}
  selector:
    app: {{ .Values.postgres.deployment.appLabel }}
