---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.studentsApi.deployment.name }}
  namespace: {{ .Values.studentsApi.namespace }}
spec:
  replicas: {{ .Values.studentsApi.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.studentsApi.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.studentsApi.deployment.appLabel }}
    spec:
      nodeSelector:
        type: {{ .Values.studentsApi.deployment.nodeSelector | quote }}
      initContainers:
      - name: {{ .Values.studentsApi.deployment.initContainer.name }}
        image: {{ .Values.studentsApi.deployment.initContainer.image | quote }}
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.studentsApi.secrets.name | quote }}
              key: DATABASE_URL
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.studentsApi.secrets.name | quote }}
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.studentsApi.secrets.name | quote }}
              key: POSTGRES_USER
        command: {{ .Values.studentsApi.deployment.initContainer.command }}
      containers:
      - name: {{ .Values.studentsApi.deployment.container.name }}
        image: {{ .Values.studentsApi.deployment.container.image | quote }}
        command: {{ .Values.studentsApi.deployment.container.command }}
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.studentsApi.secrets.name | quote }}
              key: DATABASE_URL
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.studentsApi.secrets.name | quote }}
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.studentsApi.secrets.name | quote }}
              key: POSTGRES_USER
        ports:
        - containerPort: {{ .Values.studentsApi.deployment.container.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.studentsApi.service.name }}
  namespace: {{ .Values.studentsApi.namespace }}
spec:
  ports:
  - port: {{ .Values.studentsApi.service.port }}
    targetPort: {{ .Values.studentsApi.service.targetPort }}
  selector:
    app: {{ .Values.studentsApi.deployment.appLabel }}
