apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Values.vaultToken.namespace }}
data:
  token: {{ .Values.vaultToken.token }}


# i.e :- echo -n "$(jq -r '.root_token' cluster-keys.json)" | base64

