apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-postgres
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: kube-secret-postgres-db
  data:
  - secretKey: DATABASE_URL
    remoteRef:
        key: postgres-secrets
        property: DATABASE_URL
  - secretKey: POSTGRES_USER
    remoteRef:
        key: postgres-secrets
        property: POSTGRES_USER
  - secretKey: POSTGRES_HOST
    remoteRef:
        key: postgres-secrets
        property: POSTGRES_HOST
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
        key: postgres-secrets
        property: POSTGRES_PASSWORD
  - secretKey: POSTGRES_DB
    remoteRef:
        key: postgres-secrets
        property: POSTGRES_DB
  - secretKey: PGDATA
    remoteRef:
        key: postgres-secrets
        property: PGDATA

