name: CI Pipeline

on:
  push:
    branches:
      - milestone-4
    paths:
      - milestone-4/**
      - milestone-9/**
  workflow_dispatch:

env:
  IMAGE_VERSION: 2.2.0
  MILESTONE_4_DIR: milestone-4
  MILESTONE_9_DIR: milestone-9

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          working-directory: ${{ env.MILESTONE_4_DIR }}

      - name: Install dependencies
        run: make install
        working-directory: ${{ env.MILESTONE_4_DIR }}

      - name: Run tests
        run: make test
        working-directory: ${{ env.MILESTONE_4_DIR }}

      - name: Perform code linting
        run: make lint
        working-directory: ${{ env.MILESTONE_4_DIR }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.MILESTONE_4_DIR }}
          push: true
          tags: chinmayk12/student-api:${{ env.IMAGE_VERSION }}

      - name: Update image tag in values.yaml
        run: |
          sed -i 's/image: chinmayk12\/student-api:[^ ]*/image: chinmayk12\/student-api:${{ env.IMAGE_VERSION }}/g' helm-chart/values.yaml
        working-directory: ${{ env.MILESTONE_9_DIR }}

      - name: Commit and push updated values.yaml
        run: |
          git config --local user.email "chinmay.kubal@one2n.in"
          git config --local user.name "chinmaykubal-one2n"
          git add helm-chart/values.yaml
          git commit -m "Updated image tag to chinmayk12/student-api:${{ env.IMAGE_VERSION }}"
          git push
        # working-directory: ${{ env.MILESTONE_9_DIR }}
